name: FEMlium CI

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - master
  schedule:
    - cron: "0 21 * * SUN"
  workflow_dispatch:

jobs:
  test:
    if: >-
      (
        (
          github.event_name == 'schedule'
          && github.repository == 'FEMlium/FEMlium'
        ) || (
            github.event_name != 'schedule'
            && !(
              contains(github.event.head_commit.message, '[ci skip]')
              || contains(github.event.head_commit.message, '[skip ci]')
            )
        )
      )
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - backend: none
            container: ubuntu
            setup_container: |
              apt-get -qq update
              apt-get -qq install git-lfs
            setup_dependencies: |
              export DEBIAN_FRONTEND="noninteractive"
              apt-get install -qq `apt-cache depends gmsh | awk '/Depends:/{print$2}'`
              apt-get install -qq python3-pip
              pip3 -q install --upgrade matplotlib meshio numpy
          - backend: dolfin
            container: quay.io/fenicsproject/dev
            setup_container: |
              apt-get -qq update
              apt-get -qq install git-lfs
            setup_dependencies: |
              export DEBIAN_FRONTEND="noninteractive"
              apt-get install -qq `apt-cache depends gmsh | awk '/Depends:/{print$2}'`
              pip3 -q install --upgrade meshio
              CC="mpicc" HDF5_MPI="ON" pip3 install --no-binary=h5py h5py==2.10.0
          - backend: dolfinx
            container: dolfinx/dolfinx
            setup_container: |
              apt-get -qq update
              apt-get -qq install git-lfs
            setup_dependencies: |
              rm -rf /usr/local/gmsh-*-Linux64-sdk
              pip3 -q install --upgrade itkwidgets meshio Pygments pyvista
          - backend: firedrake
            container: firedrakeproject/firedrake
            setup_container: |
              apt-get -qq update
              apt-get -qq install git-lfs
            setup_dependencies: |
              export DEBIAN_FRONTEND="noninteractive"
              apt-get install -qq xorg
              pip3 -q install --upgrade pip

      fail-fast: false
    container:
      image: ${{ matrix.container }}
      options: --user root
    steps:
      - name: Setup container
        run: ${{ matrix.setup_container }}
      - uses: actions/checkout@v1
        with:
          lfs: true
      - name: Install dependencies
        run: |
          ${{ matrix.setup_dependencies }}
          echo "Test dependencies"
          pip3 -q install --upgrade pyproj pytest pytest-flake8 pytest-xdist
          echo "Tutorial dependencies"
          pip3 -q install --upgrade gmsh jupyter
          PYTHON_VERSION=$(python3 -c 'import sys; print("python" + str(sys.version_info.major) + "." + str(sys.version_info.minor))')
          rm -rf /usr/local/lib/${PYTHON_VERSION}/site-packages/gmsh-*-Linux64-sdk/lib/__pycache__
          ln -s /usr/local/lib/${PYTHON_VERSION}/site-packages/gmsh-*-Linux64-sdk/lib/* /usr/local/lib/${PYTHON_VERSION}/dist-packages/
          ls -alrt /usr/local/lib/${PYTHON_VERSION}/dist-packages/
      - name: Install FEMlium
        run: pip3 install .
      - name: Run flake8 checks
        run: |
          pytest --flake8 -m flake8 .
          pytest --flake8 -m flake8 .github
      - name: Run unit tests
        run: pytest -n auto tests/unit
      - name: Run tutorials
        run: pytest -n auto tutorials

  jupyter:
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - name: Install dependencies
        run: |
          export DEBIAN_FRONTEND="noninteractive"
          sudo apt-get -qq update
          sudo pip3 -q install --upgrade setuptools
          sudo pip3 -q install --upgrade pip
          sudo pip3 -q install --upgrade jupyter nbformat
      - name: Check for stray outputs, counts and metadata in ipynb files
        uses: ./.github/actions/jupyter/check_metadata
      - name: Upload notebooks to website
        if: github.ref == 'refs/heads/master'
        uses: ./.github/actions/jupyter/upload_to_website
