name: FEMlium CI

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - backend: none
            container: debian:testing
          - backend: dolfinx-v0.8.0
            container: ghcr.io/fenics/dolfinx/dolfinx:v0.8.0
          - backend: dolfinx-v0.9.0
            container: ghcr.io/fenics/dolfinx/dolfinx:v0.9.0
          - backend: dolfinx-stable
            container: ghcr.io/fenics/dolfinx/dolfinx:stable
          - backend: dolfinx-nightly
            container: ghcr.io/fenics/dolfinx/dolfinx:nightly
          - backend: firedrake-2025.4.0
            container: firedrakeproject/firedrake-vanilla-default:2025.4.0.post0
          - backend: firedrake-2025.4.1
            container: firedrakeproject/firedrake-vanilla-default:2025.4.1
          - backend: firedrake-2025.4.2
            container: firedrakeproject/firedrake-vanilla-default:2025.4.2
          - backend: firedrake-latest
            container: firedrakeproject/firedrake-vanilla-default:latest
      fail-fast: false
    container: ${{ matrix.container }}
    steps:
      - name: Setup git
        run: |
          export DEBIAN_FRONTEND="noninteractive"
          apt update -y -q
          apt install -y -qq git
      - uses: actions/checkout@v4
      - name: Setup container
        run: |
          export DEBIAN_FRONTEND="noninteractive"
          apt update -y -q
          apt install -y -qq xvfb
          if [[ "${{ matrix.backend }}" == "dolfinx"* ]]; then
            :
          elif [[ "${{ matrix.backend }}" == "firedrake"* ]]; then
            apt install -y -qq xorg
            rm /usr/lib/python3.*/EXTERNALLY-MANAGED
          else
            apt install -y -qq python3-mpi4py python3-numpy python3-pip xorg
            rm /usr/lib/python3.*/EXTERNALLY-MANAGED
          fi
          if [[ "${{ matrix.backend }}" == "dolfinx-v0.8.0"* ]]; then
            python3 -m pip uninstall -y ruff
          fi
        shell: bash
      - name: Install FEMlium
        run: |
          if [[ "${{ matrix.backend }}" == "dolfinx"* ]]; then
            python3 -m pip install .[backend_dolfinx,docs,lint,tests,tutorials]
          elif [[ "${{ matrix.backend }}" == "firedrake"* ]]; then
            python3 -m pip install .[backend_firedrake,docs,lint,tests,tutorials]
          else
            python3 -m pip install .[docs,lint,tests,tutorials]
          fi
      - name: Run ruff on python files
        run: |
          python3 -m ruff check .
      - name: Run isort on python files
        run: |
          python3 -m isort --check --diff .
      - name: Run yamllint on workflows
        run: |
          python3 -m yamllint -d "{extends: default, rules: {document-start: {present: false}, line-length: disable, truthy: {check-keys: false}}}" .
      - name: Run documentation generation
        run: |
          cd docs && python3 -m sphinx -W -b html . build/html
      - name: Run unit tests
        run: |
          COVERAGE_FILE=.coverage_unit_${{ matrix.backend }} python3 -m coverage run --source=femlium -m pytest tests/unit
      - name: Generate tutorial files
        run: |
          NO_TESTS_COLLECTED=5
          python3 -m pytest --ipynb-action=create-notebooks tutorials || (($?==$NO_TESTS_COLLECTED))
        shell: bash
      - name: Run ruff on tutorial files
        run: |
          python3 -m nbqa ruff .
      - name: Run isort on tutorial files
        run: |
          python3 -m nbqa isort --check --diff .
      - name: Check for stray outputs, counts and metadata in ipynb files
        uses: RBniCS/check-jupyter-metadata-action@main
        with:
          pattern: "tutorials/**/*.ipynb"
      - name: Run tutorials
        run: |
          export DISPLAY=":99"
          Xvfb $DISPLAY -screen 0 1024x768x24 > /dev/null 2>&1 &
          COVERAGE_FILE=.coverage_tutorials_${{ matrix.backend }} python3 -m pytest --coverage-source=femlium tutorials
      - name: Store coverage reports as artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-${{ matrix.backend }}
          path: |
            .coverage*
          include-hidden-files: true
          retention-days: 1
      - name: Upload tutorials logs as an artifact in case of failure
        if: failure() || cancelled()
        uses: actions/upload-artifact@v4
        with:
          name: "tutorials-logs-${{ matrix.backend }}"
          path: |
            tutorials/**/.ipynb_pytest/**/*.log*
          include-hidden-files: true

  combine_coverage:
    runs-on: ubuntu-latest
    container: debian:testing
    needs: [test]
    steps:
      - uses: actions/checkout@v4
      - name: Setup container
        run: |
          export DEBIAN_FRONTEND="noninteractive"
          apt update -y -q
          apt install -y -qq python3-pip
          rm /usr/lib/python3.*/EXTERNALLY-MANAGED
          python3 -m pip -q install coverage[toml]
      - name: Download coverage reports from artifacts
        uses: actions/download-artifact@v4
      - name: Combine coverage reports
        run: |
          python3 -m coverage combine coverage-*/.coverage*
          python3 -m coverage report --fail-under=100 --show-missing --skip-covered

  warn:
    runs-on: ubuntu-latest
    if: github.repository == 'FEMlium/FEMlium' && github.ref == 'refs/heads/main' && github.event_name == 'schedule'
    steps:
      - name: Warn if scheduled workflow is about to be disabled
        uses: fem-on-colab/warn-workflow-about-to-be-disabled-action@main
        with:
          workflow-filename: ci.yml
          days-elapsed: 55
