name: FEMlium CI

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - master
  schedule:
    - cron: "0 21 * * SUN"
  workflow_dispatch:

jobs:
  test:
    if: >-
      (
        (
          github.event_name == 'schedule'
          && github.repository == 'FEMlium/FEMlium'
        ) || (
            github.event_name != 'schedule'
            && !(
              contains(github.event.head_commit.message, '[ci skip]')
              || contains(github.event.head_commit.message, '[skip ci]')
            )
        )
      )
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - backend: none
            container: ubuntu
            setup_container: |
              apt-get -qq update
              apt-get -qq install git-lfs
            setup_dependencies: |
              export DEBIAN_FRONTEND="noninteractive"
              apt-get install -qq `apt-cache depends gmsh | awk '/Depends:/{print$2}'`
              apt-get install -qq python3-pip
              pip3 -q install --upgrade matplotlib meshio numpy
            list_notebooks: |
              readarray -d '' GENERATE_MESH < <(find . -type f -name "generate_mesh*.ipynb" -print0)
              readarray -d '' MESHIO < <(find . -type f -name "tutorial_*_meshio.ipynb" -print0)
              list_notebooks=()
              list_notebooks+=("${GENERATE_MESH[@]}")
              list_notebooks+=("${MESHIO[@]}")
              echo "::set-output name=list_notebooks::${list_notebooks[@]}"
          - backend: dolfin
            container: quay.io/fenicsproject/dev
            setup_container: |
              apt-get -qq update
              apt-get -qq install git-lfs
            setup_dependencies: |
              export DEBIAN_FRONTEND="noninteractive"
              apt-get install -qq `apt-cache depends gmsh | awk '/Depends:/{print$2}'`
              pip3 -q install --upgrade meshio nbclient
              CC="mpicc" HDF5_MPI="ON" pip3 install --no-binary=h5py h5py==2.10.0
            list_notebooks: |
              readarray -d '' DOLFIN < <(find . -type f -name "tutorial_*_dolfin.ipynb" -print0)
              list_notebooks=()
              list_notebooks+=("${DOLFIN[@]}")
              echo "::set-output name=list_notebooks::${list_notebooks[@]}"
          - backend: dolfinx
            container: dolfinx/dolfinx
            setup_container: |
              apt-get -qq update
              apt-get -qq install git-lfs
            setup_dependencies: |
              rm -rf /usr/local/gmsh-*-Linux64-sdk
              pip3 -q install --upgrade itkwidgets meshio Pygments pyvista
            list_notebooks: |
              readarray -d '' DOLFINX < <(find . -type f -name "tutorial_*_dolfinx.ipynb" -print0)
              list_notebooks=()
              list_notebooks+=("${DOLFINX[@]}")
              echo "::set-output name=list_notebooks::${list_notebooks[@]}"
          - backend: firedrake
            container: firedrakeproject/firedrake
            setup_container: |
              apt-get -qq update
              apt-get -qq install git-lfs
              echo "/home/firedrake/firedrake/bin" >> $GITHUB_PATH
            setup_dependencies: |
              export DEBIAN_FRONTEND="noninteractive"
              apt-get install -qq xorg
              pip3 -q install --upgrade pip
            list_notebooks: |
              readarray -d '' FIREDRAKE < <(find . -type f -name "tutorial_*_firedrake.ipynb" -print0)
              list_notebooks=()
              list_notebooks+=("${FIREDRAKE[@]}")
              echo "::set-output name=list_notebooks::${list_notebooks[@]}"

      fail-fast: false
    container:
      image: ${{ matrix.container }}
      options: --user root
    steps:
      - name: Setup container
        run: ${{ matrix.setup_container }}
      - uses: actions/checkout@v1
        with:
          lfs: true
      - name: Install dependencies
        run: |
          ${{ matrix.setup_dependencies }}
          echo "Test dependencies"
          pip3 -q install --upgrade pyproj pytest pytest-flake8 pytest-xdist
          echo "Tutorial dependencies"
          pip3 -q install --upgrade gmsh jupyter nbconvert
          PYTHON_VERSION=$(python3 -c 'import sys; print("python" + str(sys.version_info.major) + "." + str(sys.version_info.minor))')
          rm -rf /usr/local/lib/${PYTHON_VERSION}/site-packages/gmsh-*-Linux64-sdk/lib/__pycache__
          ln -s /usr/local/lib/${PYTHON_VERSION}/site-packages/gmsh-*-Linux64-sdk/lib/* /usr/local/lib/${PYTHON_VERSION}/dist-packages/
      - name: Install FEMlium
        run: pip3 install .
      - name: Run flake8 checks
        run: |
          pytest --flake8 -m flake8 .
          pytest --flake8 -m flake8 .github
      - name: Check for stray outputs, counts and metadata in ipynb files
        uses: ./.github/actions/jupyter/check_metadata
      - name: Run unit tests
        run: pytest -n auto tests/unit
      - name: Run tutorials
        run: pytest -n auto tutorials
      - name: Get notebooks to be converted
        id: list_notebooks
        run: ${{ matrix.list_notebooks }}
        shell: bash
      - name: Convert notebooks
        uses: ./.github/actions/jupyter/convert
        with:
          list_notebooks: ${{ steps.list_notebooks.outputs.list_notebooks }}
      - name: Upload notebooks to website
        if: github.repository == 'FEMlium/FEMlium' && github.ref == 'refs/heads/master'
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.REPO_ACCESS_TOKEN }}
          external_repository: FEMlium/femlium.github.io
          publish_dir: _build/html
          keep_files: true
          user_name: 'GitHub Actions'
          user_email: '41898282+github-actions[bot]@users.noreply.github.com'
