name: CI (against releases)

on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:
  workflow_call:

jobs:
  # Test latest released version on PyPI against the workflow on the current main branch.
  # If main becomes incompatible with the latest version on PyPI then temporarily
  # comment out this test, and restore it on the next PyPI release.

  test_main_branch_against_latest_release_from_pypi:
    uses: FEMlium/FEMlium/.github/workflows/ci.yml@main
    with:
      ref: main
      index: PyPI
      combine_coverage: false

  # Test released versions on github or PyPI against the workflow on the corresponding git tag.

  test_0_1_0_installing_from_github:
    uses: FEMlium/FEMlium/.github/workflows/ci.yml@v0.1.0.post1
    with:
      ref: v0.1.0.post1
      combine_coverage: false

  test_0_1_0_installing_from_pypi_versioned:
    uses: FEMlium/FEMlium/.github/workflows/ci.yml@v0.1.0.post1
    with:
      ref: v0.1.0.post1
      index: PyPI
      index_version: 0.1.0
      expected_index_version: 0.1.0
      combine_coverage: false

  test_0_1_1_installing_from_github:
    uses: FEMlium/FEMlium/.github/workflows/ci.yml@v0.1.1
    with:
      ref: v0.1.1
      combine_coverage: false

  test_0_1_1_installing_from_pypi_versioned:
    uses: FEMlium/FEMlium/.github/workflows/ci.yml@v0.1.1
    with:
      ref: v0.1.1
      index: PyPI
      index_version: 0.1.1
      expected_index_version: 0.1.1
      combine_coverage: false

  test_0_1_1_installing_from_pypi_unversioned:
    uses: FEMlium/FEMlium/.github/workflows/ci.yml@v0.1.1
    with:
      ref: v0.1.1
      index: PyPI
      expected_index_version: 0.1.1
      combine_coverage: false

  warn:
    runs-on: ubuntu-latest
    if: github.repository == 'FEMlium/FEMlium' && github.ref == 'refs/heads/main' && github.event_name == 'schedule'
    steps:
      - name: Warn if scheduled workflow is about to be disabled
        uses: fem-on-colab/warn-workflow-about-to-be-disabled-action@main
        with:
          workflow-filename: ci_against_releases.yml
          days-elapsed: 50
