name: CI (against releases)

on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:
  workflow_call:

jobs:
  warn:
    runs-on: ubuntu-latest
    if: github.repository == 'FEMlium/FEMlium' && github.ref == 'refs/heads/main' && github.event_name == 'schedule'
    steps:
      - name: Warn if scheduled workflow is about to be disabled
        uses: fem-on-colab/warn-workflow-about-to-be-disabled-action@main
        with:
          workflow-filename: ci_against_releases.yml
          days-elapsed: 50
